---
title             : "Conducting developmental research online vs. in-person: A meta-analysis"
shorttitle        : "Conducting developmental research online"

author: 
  - name          : "Aaron Chuey"
    affiliation   : "1"
    corresponding : yes    # Define only one corresponding author
    email         : "chuey@stanford.edu"
    role:         # Contributorship roles (e.g., CRediT, https://casrai.org/credit/)
      - "Conceptualization, Methodology, Formal analysis, Data Curation, Visualization, Writing - Original Draft"
  - name          : "Veronica Boyce"
    affiliation   : "1"
    email         : "vboyce@stanford.edu"
    role:
      - "Conceptualization, Methodology, Formal analysis, Data Curation, Visualization, Writing - Review & Editing"
  - name          : "Anjie Cao"
    affiliation   : "1"
    email         : "anjiecao@stanford.edu"
    role:
      - "Conceptualization, Methodology, Formal analysis, Data Curation, Visualization, Writing - Review & Editing"
  - name          : "Michael C. Frank"
    affiliation   : "1"
    email         : "mcfrank@stanford.edu"
    role:
      - "Conceptualization, Methodology, Formal analysis, Data Curation, Visualization, Writing - Review & Editing, Supervision"

affiliation:
  - id            : "1"
    institution   : "Stanford University, Department of Psychology"

abstract: |
  An increasing number of psychological experiments with children are being conducted using online platforms, in part due to the COVID-19 pandemic. Individual replications have compared the findings of particular experiments online and in-person, but the general effect of data collection method on data collected from children is still unknown. Therefore, the goal of the current meta-analysis is to estimate the average difference in effect size for developmental studies conducted online compared to the same studies conducted in-person. Our pre-registered analysis includes 211 effect sizes calculated from 30 papers with 3282 children, ranging in age from four months to six years. The estimated effect size for studies conducted online was slightly smaller than for their counterparts conducted in-person, a difference of d=-.05, but this difference was not significant, 95% CI=[-.17, .07]. We examined several potential moderators of the effect of online testing, including the role of dependent measure (looking vs verbal), online study method (moderated vs unmoderated), and age, but none of these were significant. The literature to date thus suggests -- on average -- small differences in results between in-person and online experimentation for young children.
  
keywords          : "Methodology, Meta-analysis, Development, Online studies"
wordcount         : "X"
bibliography      : "r-references.bib"
annotate_references: yes

floatsintext      : yes
linenumbers       : yes
draft             : no
mask              : no

figurelist        : no
tablelist         : no
footnotelist      : no

classoption       : "man"
csl               : "apa7.csl"
output            : papaja::apa6_pdf
---

```{r setup, include = FALSE}
library(papaja)
library(here)
library(tidyverse)
library(wesanderson)
library(googlesheets4)
library(metafor)
library(kableExtra)
library(patchwork)


r_refs("r-references.bib")
here::i_am("writing/OnlineMA_main.Rmd")

knitr::opts_knit$set(root.dir = here())
knitr::opts_chunk$set(
                      echo=F, warning=F, 
                      message=F, sanitize = T)

```

```{r analysis-preferences}
# Seed for random number generation
set.seed(42)
knitr::opts_chunk$set(cache.extra = knitr::rand_seed)
```

<!-- # Public Significance Statement

For many families, interacting with a researcher online could be their first experience with a scientist, providing developmental science with an unprecedented outreach opportunity. However, to ensure that online research lives up to its potential, it is important to understand whether developmental data obtained online is comparable to data collected in-person. The current meta-analysis finds that studies with children conducted online produce generally similar effect sizes as those conducted in-person, which should empower researchers to make the most of this emerging data collection and outreach opportunity. -->

# Introduction 


```{r child = "writing/sections/01_introduction.Rmd"}
```

# Methods 


```{r child = "writing/sections/02_methods.Rmd"}
```

# Results 


```{r child = "writing/sections/03_results.Rmd"}
```

# Discussion


```{r child = "writing/sections/04_discussion.Rmd"}
```


\newpage

# References

::: {#refs custom-style="Bibliography"}
:::
